//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.HotReload.Extension {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.Forms.HotReload.Extension.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Connection_Failed_Message {
            get {
                return ResourceManager.GetString("Connection_Failed_Message", resourceCulture);
            }
        }
        
        public static string Device_Offline_Message {
            get {
                return ResourceManager.GetString("Device_Offline_Message", resourceCulture);
            }
        }
        
        public static string Global_ProductDetails {
            get {
                return ResourceManager.GetString("Global_ProductDetails", resourceCulture);
            }
        }
        
        public static string Global_ProductName {
            get {
                return ResourceManager.GetString("Global_ProductName", resourceCulture);
            }
        }
        
        public static string Global_Warning {
            get {
                return ResourceManager.GetString("Global_Warning", resourceCulture);
            }
        }
        
        public static string MainDialog_Title {
            get {
                return ResourceManager.GetString("MainDialog_Title", resourceCulture);
            }
        }
        
        public static string Update_Failed_Message {
            get {
                return ResourceManager.GetString("Update_Failed_Message", resourceCulture);
            }
        }
        
        public static string MainDialog_EnterIp {
            get {
                return ResourceManager.GetString("MainDialog_EnterIp", resourceCulture);
            }
        }
        
        public static string MainDialog_ProtocolPostfix {
            get {
                return ResourceManager.GetString("MainDialog_ProtocolPostfix", resourceCulture);
            }
        }
        
        public static string MainDialog_IpAddressPostfix {
            get {
                return ResourceManager.GetString("MainDialog_IpAddressPostfix", resourceCulture);
            }
        }
        
        public static string MainDialog_SaveConfiguration {
            get {
                return ResourceManager.GetString("MainDialog_SaveConfiguration", resourceCulture);
            }
        }
        
        public static string MainDialog_MoreInfo_0 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_0", resourceCulture);
            }
        }
        
        public static string MainDialog_MoreInfo_1 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_1", resourceCulture);
            }
        }
        
        public static string MainDialog_MoreInfo_2 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_2", resourceCulture);
            }
        }
        
        public static string MainDialog_MoreInfo_Url {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_Url", resourceCulture);
            }
        }
        
        public static string MainDialog_Connect {
            get {
                return ResourceManager.GetString("MainDialog_Connect", resourceCulture);
            }
        }
        
        public static string MainDialog_IpIncorrect {
            get {
                return ResourceManager.GetString("MainDialog_IpIncorrect", resourceCulture);
            }
        }
        
        public static string Connection_NoDevicesConnected_Message {
            get {
                return ResourceManager.GetString("Connection_NoDevicesConnected_Message", resourceCulture);
            }
        }
        
        public static string InfoBar_DontShowAgain {
            get {
                return ResourceManager.GetString("InfoBar_DontShowAgain", resourceCulture);
            }
        }
        
        public static string InfoBar_EnableExtension {
            get {
                return ResourceManager.GetString("InfoBar_EnableExtension", resourceCulture);
            }
        }
        
        public static string InfoBar_ExtensionNotEnabled {
            get {
                return ResourceManager.GetString("InfoBar_ExtensionNotEnabled", resourceCulture);
            }
        }
        
        public static string Unknown_Error {
            get {
                return ResourceManager.GetString("Unknown_Error", resourceCulture);
            }
        }
    }
}
