//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.HotReload.Extension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Forms.HotReload.Extension.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on trying to connect occured..
        /// </summary>
        public static string Connection_Failed_Message {
            get {
                return ResourceManager.GetString("Connection_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info] No devices connected..
        /// </summary>
        public static string Connection_NoDevicesConnected_Message {
            get {
                return ResourceManager.GetString("Connection_NoDevicesConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Check that entered device IP is correct or device screen is unlocked and app running in foreground..
        /// </summary>
        public static string Device_Offline_Message {
            get {
                return ResourceManager.GetString("Device_Offline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My awesome Detailed Info.
        /// </summary>
        public static string Global_ProductDetails {
            get {
                return ResourceManager.GetString("Global_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Descript.
        /// </summary>
        public static string Global_ProductName {
            get {
                return ResourceManager.GetString("Global_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Global_Warning {
            get {
                return ResourceManager.GetString("Global_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this again.
        /// </summary>
        public static string InfoBar_DontShowAgain {
            get {
                return ResourceManager.GetString("InfoBar_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable it!.
        /// </summary>
        public static string InfoBar_EnableExtension {
            get {
                return ResourceManager.GetString("InfoBar_EnableExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Forms HotReload is not enabled..
        /// </summary>
        public static string InfoBar_ExtensionNotEnabled {
            get {
                return ResourceManager.GetString("InfoBar_ExtensionNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string MainDialog_Connect {
            get {
                return ResourceManager.GetString("MainDialog_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices connections list:.
        /// </summary>
        public static string MainDialog_EnterIp {
            get {
                return ResourceManager.GetString("MainDialog_EnterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  :.
        /// </summary>
        public static string MainDialog_IpAddressPostfix {
            get {
                return ResourceManager.GetString("MainDialog_IpAddressPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address is not in a correct format.
        /// </summary>
        public static string MainDialog_IpIncorrect {
            get {
                return ResourceManager.GetString("MainDialog_IpIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more info and issue reporting .
        /// </summary>
        public static string MainDialog_MoreInfo_0 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string MainDialog_MoreInfo_1 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string MainDialog_MoreInfo_2 {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AndreiMisiukevich/HotReload.
        /// </summary>
        public static string MainDialog_MoreInfo_Url {
            get {
                return ResourceManager.GetString("MainDialog_MoreInfo_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ://.
        /// </summary>
        public static string MainDialog_ProtocolPostfix {
            get {
                return ResourceManager.GetString("MainDialog_ProtocolPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration.
        /// </summary>
        public static string MainDialog_SaveConfiguration {
            get {
                return ResourceManager.GetString("MainDialog_SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Forms HotReload.
        /// </summary>
        public static string MainDialog_Title {
            get {
                return ResourceManager.GetString("MainDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on trying to make update occured..
        /// </summary>
        public static string Update_Failed_Message {
            get {
                return ResourceManager.GetString("Update_Failed_Message", resourceCulture);
            }
        }
    }
}
